export const permissions = {
  admin: {
    addUser: true,
    editUser: true,
    deleteUser: true,
    createBug: true,
    editBug: true,
    deleteBug: true,
    assignBug: true,
    changeStatus: true,
    manageUsers: true,
    viewReports: true,
    viewAction: true,
  },
  qa: {
    addUser: false,
    editUser: false,
    deleteUser: false,
    createBug: true,
    editBug: false,
    deleteBug: false,
    assignBug: false,
    changeStatus: false,
    manageUsers: false,
    viewReports: true,
    viewAction: false,
  },
  developer: {
    addUser: false,
    editUser: false,
    deleteUser: false,
    createBug: false,
    editBug: true,
    deleteBug: false,
    assignBug: false,
    changeStatus: true,
    manageUsers: false,
    viewReports: false,
    viewAction: true,
  },
};
