export default [
  {
    id: "1",
    title: "Login issue",
    severity: "Medium",
    status: "Open",
    assigned: "John",
    created: "2024-04-20",
  },
  {
    id: "2",
    title: "Mobile crash",
    severity: "Critical",
    status: "Close",
    assigned: "Lee",
    created: "2024-04-20",
  },
  {
    id: "3",
    title: "Label missing",
    severity: "Low",
    status: "Open",
    assigned: "Rohit",
    created: "2024-04-20",
  },
  {
    id: "4",
    title: "Dropdown issue",
    severity: "High",
    status: "Close",
    assigned: "Virat",
    created: "2024-04-20",
  },
  {
    id: "5",
    title: "Color mismatch",
    severity: "Low",
    status: "Open",
    assigned: "David",
    created: "2024-04-20",
  },
  {
    id: "6",
    title: "Login issue",
    severity: "High",
    status: "Open",
    assigned: "John",
    created: "2024-04-20",
  },
  {
    id: "7",
    title: "Login issue",
    severity: "High",
    status: "progress",
    assigned: "lee",
    created: "2024-04-20",
  },
  {
    id: "8",
    title: "Login issue",
    severity: "High",
    status: "progress",
    assigned: "John",
    created: "2024-04-20",
  },
  {
    id: "9",
    title: "Login issue",
    severity: "critical",
    status: "Open",
    assigned: "John",
    created: "2024-04-20",
  },
  {
    id: "10",
    title: "app crash issue",
    severity: "low",
    status: "Open",
    assigned: "John",
    created: "2024-04-20",
  },
];
